import { useEffect, useMemo, useState } from "react";
import { ArrowUpLeft, BarChart3, ExternalLink, Filter, Globe2, ShoppingBag, Smartphone, X } from "lucide-react";
import { Link } from "wouter";
import SiteLayout from "../components/SiteLayout";
import { useTheme } from "../contexts/ThemeContext";

const MOCKUPS = { nexus: "/assets/nexus.svg", motion: "/assets/motion.svg", lumen: "/assets/lumen.svg" };
const TEMPLATE_IMAGES = { store: "/assets/store.svg", news: "/assets/news.svg" };

type Project = { title: string; slug: string; cat: string; industry: string; year: string; description: string; result: string; label: string; icon: typeof BarChart3; theme: string; visual: keyof typeof MOCKUPS; challenge: string; solution: string; outcome: string };
type TemplateProject = { slug: "store" | "news"; title: string; eyebrow: string; description: string; client: string; stack: string; result: string; theme: string; image: string; tags: string[] };

function CaseVisual({ kind, title, onOpen, label }: { kind: keyof typeof MOCKUPS; title: string; onOpen: () => void; label: string }) { return <button type="button" className={`case-card-visual visual-${kind}`} onClick={onOpen} aria-label={`${label}: ${title}`}><img src={MOCKUPS[kind]} alt={`${title} QYLAKI product mockup`} loading="lazy"/><span className="visual-signal">QYLAKI / SIGNAL</span></button>; }

export default function Work() {
  const { t, language } = useTheme(); const ar = language === "ar";
  const [category, setCategory] = useState("all"); const [industry, setIndustry] = useState("all"); const [selected, setSelected] = useState<string | null>(null); const [templateSelected, setTemplateSelected] = useState<TemplateProject["slug"] | null>(null);
  const projects: Project[] = [
    { title: "NEXUS", slug: "nexus", cat: "platforms", industry: "finance", year: "2025", description: t("clarity"), result: "+32%", label: t("measurable"), icon: BarChart3, theme: "project-indigo", visual: "nexus", challenge: t("nexusChallenge"), solution: t("nexusSolution"), outcome: t("nexusOutcome") },
    { title: "MOTION", slug: "motion", cat: "apps", industry: "health", year: "2025", description: t("productsText"), result: "4.8/5", label: t("experience"), icon: Smartphone, theme: "project-orange", visual: "motion", challenge: t("motionChallenge"), solution: t("motionSolution"), outcome: t("motionOutcome") },
    { title: "LUMEN", slug: "lumen", cat: "stores", industry: "commerce", year: "2024", description: t("ecommerceText"), result: "+48%", label: t("impact"), icon: ShoppingBag, theme: "project-green", visual: "lumen", challenge: t("lumenChallenge"), solution: t("lumenSolution"), outcome: t("lumenOutcome") },
  ];
  const templates: TemplateProject[] = [
    { slug: "store", title: ar ? "متجر QYLAKI" : "QYLAKI Store", eyebrow: ar ? "قالب متجر إلكتروني" : "E-commerce template", description: ar ? "تجربة متجر متعددة اللغات للملابس والإلكترونيات، مع بحث وفئات وسلة شراء وتفاصيل منتجات." : "A multilingual storefront for fashion and electronics with search, categories, cart, and product details.", client: ar ? "نموذج داخلي — QYLAKI" : "Internal concept — QYLAKI", stack: "HTML · CSS · JavaScript", result: ar ? "تجربة شراء واضحة" : "Clear shopping journey", theme: "template-store", image: TEMPLATE_IMAGES.store, tags: ar ? ["متجر", "متعدد اللغات", "سلة شراء"] : ["Store", "Multilingual", "Cart"] },
    { slug: "news", title: ar ? "أخبار العالم" : "World News", eyebrow: ar ? "قالب منصة محتوى" : "Content platform template", description: ar ? "منصة أخبار عربية بتخطيط تحريري، تصنيفات، أخبار عاجلة، بطاقات قصص، وبحث سريع." : "An Arabic editorial news platform with categories, live updates, story cards, and fast search.", client: ar ? "نموذج داخلي — QYLAKI" : "Internal concept — QYLAKI", stack: "HTML · CSS · JavaScript", result: ar ? "قراءة أسهل ومحتوى أوضح" : "Clearer editorial reading", theme: "template-news", image: TEMPLATE_IMAGES.news, tags: ar ? ["أخبار", "تحرير", "بحث"] : ["News", "Editorial", "Search"] },
  ];
  const shown = useMemo(() => projects.filter(p => (category === "all" || p.cat === category) && (industry === "all" || p.industry === industry)), [category, industry]);
  const active = projects.find(p => p.slug === selected); const activeTemplate = templates.find(p => p.slug === templateSelected); const clear = () => { setCategory("all"); setIndustry("all"); };

  useEffect(() => { const revealItems = document.querySelectorAll<HTMLElement>(".reveal-on-scroll"); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: .12 }); revealItems.forEach(item => observer.observe(item)); return () => observer.disconnect(); }, [category, industry]);
  useEffect(() => { if (!active && !activeTemplate) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelected(null); setTemplateSelected(null); } }; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; document.addEventListener("keydown", closeOnEscape); return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", closeOnEscape); }; }, [active, activeTemplate]);

  return <SiteLayout><div className="inner-page">
    <section className="page-hero page-container reveal-on-scroll"><p className="kicker">{t("pageWork")}</p><h1>{t("workHero")}<br/><em>{t("rightQuestion")}</em></h1><p className="lead">{t("workLead")}</p></section>
    <section className="template-showcase page-container reveal-on-scroll"><div className="section-heading"><div><p className="kicker">{ar ? "تجارب قابلة للعرض" : "Live-ready examples"}</p><h2>{ar ? <>مشاريع حقيقية.<br/><em>قوالب يمكنك تجربتها.</em></> : <>Real builds.<br/><em>Templates you can explore.</em></>}</h2></div><p>{ar ? "هذه النماذج صُنعت داخل QYLAKI لتوضيح مستوى التصميم والتطوير الذي يمكننا تقديمه لمشروعك." : "These concepts were built inside QYLAKI to show the level of design and engineering we can bring to your project."}</p></div><div className="template-grid">{templates.map((project, index) => <article key={project.slug} className={`template-card ${project.theme} reveal-on-scroll`} style={{ "--reveal-delay": `${index * 90}ms` } as React.CSSProperties}><button className="template-image-button" onClick={() => setTemplateSelected(project.slug)} aria-label={`${ar ? "عرض تفاصيل" : "View details"} ${project.title}`}><img src={project.image} alt={`${project.title} ${project.eyebrow}`} loading="lazy"/><span className="template-image-overlay"><ExternalLink size={18}/>{ar ? "استكشف المشروع" : "Explore project"}</span></button><div className="template-copy"><div className="template-meta"><span>{project.eyebrow}</span><Globe2 size={17}/></div><h3>{project.title}</h3><p>{project.description}</p><div className="template-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="template-bottom"><div><small>{ar ? "العميل" : "Client"}</small><strong>{project.client}</strong></div><div><small>{ar ? "التقنيات" : "Stack"}</small><strong>{project.stack}</strong></div></div></div></article>)}</div></section>
    <section className="work-archive page-container reveal-on-scroll"><div className="archive-heading"><div><p className="kicker">{ar ? "دراسات الحالة" : "Case studies"}</p><h2>{ar ? "أعمال مصممة" : "Work designed"}<br/><em>{ar ? "لتترك أثراً." : "to make an impact."}</em></h2></div><div className="smart-filter-head"><div className="filter-label"><Filter size={15} aria-hidden="true"/>{t("industry")}</div><select value={industry} onChange={e => setIndustry(e.target.value)} aria-label={t("industry")}><option value="all">{t("allIndustries")}</option><option value="finance">{t("finance")}</option><option value="health">{t("health")}</option><option value="commerce">{t("commerce")}</option></select></div></div><div className="filter-row">{[["all", "all"], ["platforms", "platforms"], ["apps", "apps"], ["stores", "stores"]].map(([key, label]) => <button key={key} type="button" className={category === key ? "filter active" : "filter"} onClick={() => setCategory(key)} aria-pressed={category === key}>{t(label)}</button>)}{(category !== "all" || industry !== "all") && <button type="button" className="filter reset" onClick={clear}><X size={13} aria-hidden="true"/>{t("all")}</button>}</div><div className="archive-grid">{shown.map(({ title, slug, cat, year, description, result, label, icon: Icon, theme, visual }, index) => <article key={title} className={`archive-card ${theme} reveal-on-scroll`} style={{ "--reveal-delay": `${index * 70}ms` } as React.CSSProperties}><CaseVisual kind={visual} title={title} label={t("caseStudy")} onOpen={() => setSelected(slug)}/><div className="archive-top"><span>{t(cat)} / {year}</span><Icon size={20} aria-hidden="true"/></div><div className="archive-main"><h2>{title}</h2><p>{description}</p><div><strong>{result}</strong><span>{label}</span></div></div><div className="case-actions"><button type="button" className="case-preview" onClick={() => setSelected(slug)}>{t("caseStudy")}</button><Link href={`/work/${slug}`} className="case-open">{t("caseStudy")} <ArrowUpLeft size={17} aria-hidden="true"/></Link></div></article>)}</div>{shown.length === 0 && <div className="filter-empty">{t("allIndustries")}</div>}</section>
    <section className="work-cta page-container reveal-on-scroll"><p className="kicker">{t("important")}</p><h2>{t("next")}<br/><em>{t("rightQuestion")}</em></h2><Link href="/project" className="button primary">{t("startIdea")} <ArrowUpLeft size={17} aria-hidden="true"/></Link></section>
  </div>
  {active && <div className="case-overlay" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setSelected(null); }}><div className={`case-modal ${active.theme}`} role="dialog" aria-modal="true" aria-labelledby="case-modal-title"><button className="case-close" onClick={() => setSelected(null)} aria-label={t("caseStudy")}><X size={20}/></button><div className="case-modal-top"><span>{t(active.cat)} / {active.year}</span><active.icon size={25} aria-hidden="true"/></div><h2 id="case-modal-title">{active.title}</h2><p className="case-modal-lead">{active.description}</p><div className="case-details"><div><span>{t("challenge")}</span><p>{active.challenge}</p></div><div><span>{t("solution")}</span><p>{active.solution}</p></div><div><span>{t("outcome")}</span><p>{active.outcome}</p></div></div><div className="case-result"><strong>{active.result}</strong><span>{active.label}</span></div><Link href={`/work/${active.slug}`} className="button outline case-modal-link">{t("caseStudy")} <ArrowUpLeft size={16}/></Link></div></div>}
  {activeTemplate && <div className="case-overlay" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setTemplateSelected(null); }}><div className={`template-modal ${activeTemplate.theme}`} role="dialog" aria-modal="true" aria-labelledby="template-modal-title"><button className="case-close" onClick={() => setTemplateSelected(null)} aria-label={ar ? "إغلاق" : "Close"}><X size={20}/></button><img src={activeTemplate.image} alt={activeTemplate.title}/><div className="template-modal-copy"><p className="kicker">{activeTemplate.eyebrow}</p><h2 id="template-modal-title">{activeTemplate.title}</h2><p>{activeTemplate.description}</p><div className="template-modal-facts"><span><small>{ar ? "العميل" : "Client"}</small><strong>{activeTemplate.client}</strong></span><span><small>{ar ? "النتيجة" : "Outcome"}</small><strong>{activeTemplate.result}</strong></span><span><small>{ar ? "التقنيات" : "Stack"}</small><strong>{activeTemplate.stack}</strong></span></div><Link href="/project" className="button primary">{ar ? "ابنِ مشروعاً مشابهاً" : "Build something similar"}<ArrowUpLeft size={16}/></Link></div></div></div>}
  </SiteLayout>;
}
