import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { notifyOwner } from "./_core/notification";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { createBookingConfirmation } from "./booking-integrations";
import { createBooking, createContactSubmission, getAllBookings, getAllContactSubmissions, getContactSubmissionsByUserId, updateBooking, updateContactSubmission } from "./db";
import { invokeLLM } from "./_core/llm";

const submissionInput = z.object({ name: z.string().trim().min(1).max(160), email: z.string().trim().email().max(320), projectType: z.string().trim().max(120).optional(), message: z.string().trim().min(1).max(8000), estimateMin: z.number().int().min(0).max(1000000).optional(), estimateMax: z.number().int().min(0).max(1000000).optional(), estimateWeeks: z.number().int().min(1).max(104).optional() });
const bookingInput = z.object({ name: z.string().trim().min(1).max(160), email: z.string().trim().email().max(320), company: z.string().trim().max(180).optional(), service: z.string().trim().min(1).max(120), bookingDate: z.string().trim().min(8).max(20), bookingTime: z.string().trim().min(3).max(20), notes: z.string().trim().max(2000).optional() });
const statusInput = z.object({ id: z.number().int().positive(), status: z.enum(["new", "reviewed", "in_progress", "won", "archived"]), adminNotes: z.string().trim().max(3000).optional() });
const bookingStatusInput = z.object({ id: z.number().int().positive(), status: z.enum(["requested", "confirmed", "completed", "cancelled"]) });
const chatInput = z.object({ messages: z.array(z.object({ role: z.enum(["user", "assistant"]), content: z.string().trim().min(1).max(3000) })).min(1).max(12), language: z.enum(["ar", "en", "fr"]).default("ar") });

export const appRouter = router({
  system: router({ notifyOwner: publicProcedure.input(z.object({ title: z.string(), content: z.string() })).mutation(async ({ input }) => ({ success: await notifyOwner(input) })) }),
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  contact: router({ submit: publicProcedure.input(submissionInput).mutation(async ({ input, ctx }) => { const saved = await createContactSubmission({ userId: ctx.user?.id ?? null, name: input.name, email: input.email, projectType: input.projectType || null, message: input.message, estimateMin: input.estimateMin ?? null, estimateMax: input.estimateMax ?? null, estimateWeeks: input.estimateWeeks ?? null, status: "new" }); await notifyOwner({ title: `طلب مشروع جديد من ${input.name}`, content: `${input.email}\n${input.projectType || "مشروع عام"}\n${input.message.slice(0, 1000)}` }); return { success: true, id: saved.id } as const; }) }),
  bookings: router({ create: publicProcedure.input(bookingInput).mutation(async ({ input, ctx }) => { const saved = await createBooking({ ...input, userId: ctx.user?.id ?? null, company: input.company || null, notes: input.notes || null, status: "requested" }); const confirmation = await createBookingConfirmation({ name: input.name, email: input.email, service: input.service, date: input.bookingDate, time: input.bookingTime }); await notifyOwner({ title: `طلب حجز مكالمة من ${input.name}`, content: `${input.email}\n${input.bookingDate} ${input.bookingTime}\n${input.service}\nConfirmation email: ${confirmation.emailSent ? "sent" : "not configured"}` }); return { success: true, id: saved.id, ...confirmation } as const; }) }),
  ai: router({ chat: publicProcedure.input(chatInput).mutation(async ({ input }) => { const languageName = input.language === "ar" ? "Arabic" : input.language === "fr" ? "French" : "English"; const result = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: `You are QYLAKI's small website assistant. Answer in ${languageName}. QYLAKI is a software and digital product studio offering strategy, UX/UI, websites, stores, dashboards, and custom web products. Be concise, warm, professional, and practical. Never invent exact prices; say projects start from $60 and the final scope is quoted after understanding the project. If the user wants to start, guide them to the project form or booking page. Do not claim to be human.`, }, ...input.messages] }); const content = result.choices[0]?.message?.content; return { content: typeof content === "string" ? content : "Please use the project form or book a discovery call so we can help." }; }) }),
  dashboard: router({ requests: protectedProcedure.query(({ ctx }) => getContactSubmissionsByUserId(ctx.user.id)) }),
  admin: router({ requests: adminProcedure.query(() => getAllContactSubmissions()), bookings: adminProcedure.query(() => getAllBookings()), updateRequest: adminProcedure.input(statusInput).mutation(async ({ input }) => { await updateContactSubmission(input.id, input.status, input.adminNotes); return { success: true } as const; }), updateBooking: adminProcedure.input(bookingStatusInput).mutation(async ({ input }) => { await updateBooking(input.id, input.status); return { success: true } as const; }) }),
});
export type AppRouter = typeof appRouter;
